master:
  image: python:3
  script:
    - apt-get update -qy
    - apt-get install -qy libopenblas-dev liblapack-dev libscalapack-mpi-dev libxc-dev > apt-get.output
    - pip install flake8
    - pip install git+https://gitlab.com/ase/ase.git@3.17.0 > ase-install.output
    - sed -i "s/scalapack = False/scalapack = True/" customize.py
    - python setup.py install > gpaw-install.output
    - useradd -m user
    - su user -c 'gpaw install-data --register gpaw-datasets'
    - su user -c 'gpaw -P 1 info'
    - su user -c 'ase build H2 -V1 | gpaw -P 2 run -p mode=pw'
    - flake8 --ignore E,W --exclude "doc/platforms/*" gpaw doc
