master:
  script:
    - apt-get update -qy
    - apt-get install -qy python-dev python-numpy libopenblas-dev liblapack-dev libxc-dev python-pip
    - pip install git+https://gitlab.com/ase/ase.git@master
    - python setup.py install --user
    - ~/.local/bin/gpaw info
